sonar.projectKey=technova
sonar.projectName=TechNova Seguridad
sonar.projectVersion=1.0
sonar.sources=clientes,config
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11

sonar.exclusions=venv/**,staticfiles/**,media/**,evidencias/**,**/__pycache__/**,**/migrations/**
